version: 2
updates:
  # NPM dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'npm'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  # Docker dependencies
  - package-ecosystem: 'docker'
    directory: '/infra/dev'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'docker'
    commit-message:
      prefix: 'chore'

  - package-ecosystem: 'docker'
    directory: '/infra/prod'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'docker'
    commit-message:
      prefix: 'chore'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'chore'
