name: Cleanup Old Images

on:
  schedule:
    # Run every Sunday at 3 AM UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  cleanup:
    name: Delete Old Container Images
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      matrix:
        image: [base, app]

    steps:
      - name: Set lowercase image name
        id: image-name
        run: echo "value=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Delete old images
        continue-on-error: true
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ steps.image-name.outputs.value }}/${{ matrix.image }}
          package-type: container
          min-versions-to-keep: 10
          delete-only-untagged-versions: true
